/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import user.User;
import content.*;
import java.awt.Color;
import java.awt.GridLayout;
import java.time.LocalDate;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author laisa
 */
public class EventPage extends javax.swing.JFrame {
    
    private static User user;
    private static Event event;

    /**
     * Creates new form EventPage
     * @param user
     * @param event
     */
    public EventPage(User user, Event event) {
        EventPage.user = user;
        EventPage.event = event;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventPage = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        buttonRepeat = new javax.swing.JLabel();
        labelEventName = new javax.swing.JLabel();
        labelAddLocation = new javax.swing.JLabel();
        labelAddParticipants = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TaDa - Event");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        eventPage.setBackground(new java.awt.Color(255, 255, 255));
        eventPage.setPreferredSize(new java.awt.Dimension(1286, 690));

        footer.setBackground(new java.awt.Color(51, 51, 255));

        buttonRepeat.setBackground(new java.awt.Color(255, 255, 255));
        buttonRepeat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonRepeat.setForeground(new java.awt.Color(255, 255, 255));
        buttonRepeat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonRepeat.setText("Repeat event");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonRepeat)
                .addGap(48, 48, 48))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(buttonRepeat)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        labelEventName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelEventName.setForeground(new java.awt.Color(51, 51, 51));
        labelEventName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEventName.setText(event.getName());

        if (event.getLocation() == null){
            labelAddLocation.setText("Add location");
        }
        else {
            labelAddLocation.setText(event.getLocation().displayLocation());
        }
        labelAddLocation.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelAddLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLocationMouseClicked(evt);
            }
        });

        if (event.getParticipants() == null){
            labelAddParticipants.setText("Add participants");
        }
        else {
            labelAddParticipants.setText(event.displayParticipants());
        }
        labelAddParticipants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addParticipantsMouseClicked(evt);
            }
        });

        labelDate.setText(event.getPeriod().displayPeriod());
        labelDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout eventPageLayout = new javax.swing.GroupLayout(eventPage);
        eventPage.setLayout(eventPageLayout);
        eventPageLayout.setHorizontalGroup(
            eventPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(eventPageLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(eventPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelAddLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelEventName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelAddParticipants)
                    .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(973, Short.MAX_VALUE))
        );
        eventPageLayout.setVerticalGroup(
            eventPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eventPageLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(labelEventName)
                .addGap(24, 24, 24)
                .addComponent(labelAddLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelAddParticipants)
                .addGap(12, 12, 12)
                .addComponent(labelDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 414, Short.MAX_VALUE)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eventPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(eventPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addParticipantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addParticipantsMouseClicked
        //displayParticipantsDialog();
    }//GEN-LAST:event_addParticipantsMouseClicked

    private void addLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLocationMouseClicked
        displayLocationDialog();
    }//GEN-LAST:event_addLocationMouseClicked

    private void dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseClicked
        // displayDateDialog();
    }//GEN-LAST:event_dateMouseClicked
                                     

    private void displayLocationDialog() {
        Location location = new Location();
        JPanel panelLocation = new JPanel();
        panelLocation.setBackground(Color.WHITE);
        panelLocation.setLayout(new GridLayout(5, 2));

        // Add text field for location information
        JTextField countryTextField = new JTextField();
        JTextField cityTextField = new JTextField();
        JTextField stateTextField = new JTextField();
        JTextField streetTextField = new JTextField();
        JTextField numberTextField = new JTextField();

        // Add labels and text boxes to the panel
        panelLocation.add(new JLabel("Country:"));
        panelLocation.add(countryTextField);

        panelLocation.add(new JLabel("City:"));
        panelLocation.add(cityTextField);

        panelLocation.add(new JLabel("State:"));
        panelLocation.add(stateTextField);

        panelLocation.add(new JLabel("Street:"));
        panelLocation.add(streetTextField);

        panelLocation.add(new JLabel("Number:"));
        panelLocation.add(numberTextField);

        int result = JOptionPane.showConfirmDialog(this, panelLocation, "Add Location",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        // If the user clicks "OK", they get the entered information
        if (result == JOptionPane.OK_OPTION) {
            String country = countryTextField.getText();
            location.setCountry(country);

            String city = cityTextField.getText();
            location.setCity(city);

            String state = stateTextField.getText();
            location.setState(state);

            String street = streetTextField.getText();
            location.setStreet(street);
            

            try {
                int number = Integer.parseInt(numberTextField.getText());
                location.setNumber(number);
                
                event.setLocation(location);
                labelAddLocation.setText(event.getLocation().displayLocation());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User user1 = new User();
                Period period = new Period(LocalDate.now());
                Event event1 = new Event("Presentation", period);
                new EventPage(user1, event1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonRepeat;
    private javax.swing.JPanel eventPage;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel labelAddLocation;
    private javax.swing.JLabel labelAddParticipants;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelEventName;
    // End of variables declaration//GEN-END:variables
}
